-- =============================================================================
-- IntegratedAccSys - PostgreSQL Schema (Converted from SQL Server)
-- Generated: 2026-06-08
-- Source: Database/IntegratedAccSys_Full.sql (SQL Server 2019)
-- Target: PostgreSQL 17
-- =============================================================================
-- Conversion notes (T-SQL -> PL/pgSQL):
--   * IDENTITY(1,1)         -> GENERATED BY DEFAULT AS IDENTITY
--   * NVARCHAR(n)           -> VARCHAR(n)   (UTF-8 encoded DB)
--   * VARBINARY(MAX)        -> BYTEA
--   * NVARCHAR(MAX)         -> TEXT
--   * DATETIME              -> TIMESTAMP
--   * BIT                   -> BOOLEAN
--   * GETDATE()             -> CURRENT_TIMESTAMP
--   * NEWID()               -> gen_random_uuid()
--   * UNIQUEIDENTIFIER      -> UUID
--   * [dbo].                -> public.
--   * CREATE OR ALTER PROC  -> CREATE OR REPLACE PROCEDURE / FUNCTION
--   * SET NOCOUNT ON        -> removed (PostgreSQL behavior)
--   * IF EXISTS (...) DROP  -> DROP ... IF EXISTS
--   * DATEDIFF              -> EXTRACT(EPOCH FROM ...)/86400 or age()
--   * ISNULL(a,b)           -> COALESCE(a,b)
-- =============================================================================

-- Make sure pgcrypto is available for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA public;

-- =============================================================================
-- SECTION 2: SECURITY DOMAIN TABLES
-- =============================================================================

CREATE TABLE public.tblWindows (
    WindowID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WindowCode VARCHAR(50) UNIQUE NOT NULL,
    WindowNameAr VARCHAR(200) NOT NULL,
    WindowNameEn VARCHAR(200),
    ModuleName VARCHAR(100) NOT NULL,
    FormName VARCHAR(200),
    IsActive BOOLEAN DEFAULT TRUE,
    SortOrder INT DEFAULT 0,
    IconName VARCHAR(100),
    ParentWindowID INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt TIMESTAMP,
    Notes TEXT,
    CONSTRAINT FK_tblWindows_Parent FOREIGN KEY (ParentWindowID) REFERENCES public.tblWindows (WindowID)
);

CREATE INDEX idx_tblWindows_Module ON public.tblWindows (ModuleName);

CREATE INDEX idx_tblWindows_Parent ON public.tblWindows (ParentWindowID);

CREATE TABLE public.tblUsers (
    UserCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID VARCHAR(15) UNIQUE NOT NULL,
    UserPassword BYTEA NOT NULL,
    Salt BYTEA NOT NULL,
    UserNameAr VARCHAR(200),
    UserNameEn VARCHAR(200),
    Email VARCHAR(100),
    Phone VARCHAR(50),
    Mobile VARCHAR(50),
    IsActive BOOLEAN DEFAULT TRUE,
    IsAdmin BOOLEAN DEFAULT FALSE,
    PasswordLastChanged TIMESTAMP,
    PasswordHistory1 BYTEA,
    PasswordHistory2 BYTEA,
    LastLoginAt TIMESTAMP,
    LoginAttempts INT DEFAULT 0,
    LockedUntil TIMESTAMP,
    MustChangePassword BOOLEAN DEFAULT FALSE,
    BranchCode INT,
    Department VARCHAR(100),
    JobTitle VARCHAR(100),
    Photo BYTEA,
    IsOnline BOOLEAN DEFAULT FALSE,
    CreatedBy INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ModifiedBy INT,
    ModifiedAt TIMESTAMP,
    Notes TEXT
);

CREATE INDEX idx_tblUsers_UserID ON public.tblUsers (UserID);

CREATE INDEX idx_tblUsers_IsActive ON public.tblUsers (IsActive);

CREATE INDEX idx_tblUsers_Branch ON public.tblUsers (BranchCode);

CREATE TABLE public.tblUserRoles (
    RoleID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleName VARCHAR(50) NOT NULL UNIQUE,
    RoleNameAr VARCHAR(100) NOT NULL,
    RoleNameEn VARCHAR(100),
    Description VARCHAR(500),
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Notes TEXT
);

CREATE TABLE public.tblUserRoleAssignments (
    AssignmentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserCode INT NOT NULL,
    RoleID INT NOT NULL,
    AssignedBy INT,
    AssignedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMP,
    IsActive BOOLEAN DEFAULT TRUE,
    CONSTRAINT FK_UserRole_User FOREIGN KEY (UserCode) REFERENCES public.tblUsers (UserCode),
    CONSTRAINT FK_UserRole_Role FOREIGN KEY (RoleID) REFERENCES public.tblUserRoles (RoleID),
    CONSTRAINT UQ_UserRole_Assignment UNIQUE (UserCode, RoleID)
);

CREATE TABLE public.tblPrivileges (
    PrivilegeID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserCode INT NOT NULL,
    WindowID INT NOT NULL,
    CanDisplay BOOLEAN DEFAULT TRUE,
    CanAdd BOOLEAN DEFAULT TRUE,
    CanEdit BOOLEAN DEFAULT TRUE,
    CanDelete BOOLEAN DEFAULT TRUE,
    CanPrint BOOLEAN DEFAULT FALSE,
    CanExport BOOLEAN DEFAULT FALSE,
    CanApprove BOOLEAN DEFAULT FALSE,
    CanPost BOOLEAN DEFAULT FALSE,
    CustomPermissions TEXT,
    EffectiveFrom TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EffectiveTo TIMESTAMP,
    CreatedBy INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ModifiedBy INT,
    ModifiedAt TIMESTAMP,
    CONSTRAINT FK_Privileges_User FOREIGN KEY (UserCode) REFERENCES public.tblUsers (UserCode),
    CONSTRAINT FK_Privileges_Window FOREIGN KEY (WindowID) REFERENCES public.tblWindows (WindowID),
    CONSTRAINT UQ_UserWindow UNIQUE (UserCode, WindowID)
);

CREATE INDEX idx_Privileges_User ON public.tblPrivileges (UserCode);

CREATE INDEX idx_Privileges_Window ON public.tblPrivileges (WindowID);

CREATE TABLE public.tblSessions (
    SessionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SessionToken UUID NOT NULL UNIQUE DEFAULT gen_random_uuid (),
    UserCode INT NOT NULL,
    UserID VARCHAR(15) NOT NULL,
    BranchCode INT,
    MachineName VARCHAR(100),
    IPAddress VARCHAR(50),
    MacAddress VARCHAR(50),
    BrowserInfo VARCHAR(500),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastActivityAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMP,
    LogoutAt TIMESTAMP,
    IsActive BOOLEAN DEFAULT TRUE,
    SessionData TEXT,
    CONSTRAINT FK_Sessions_User FOREIGN KEY (UserCode) REFERENCES public.tblUsers (UserCode)
);

CREATE INDEX idx_Sessions_Token ON public.tblSessions (SessionToken);

CREATE INDEX idx_Sessions_User ON public.tblSessions (UserCode);

CREATE INDEX idx_Sessions_Expires ON public.tblSessions (ExpiresAt);

CREATE TABLE public.tblAuditLogs (
    AuditID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserCode INT,
    UserID VARCHAR(15),
    EventType VARCHAR(50) NOT NULL,
    EventCategory VARCHAR(50) NOT NULL,
    EventDescription VARCHAR(1000) NOT NULL,
    TableName VARCHAR(100),
    RecordID INT,
    OldValues TEXT,
    NewValues TEXT,
    SQLCommand TEXT
);
-- Note: AuditLogs is a representative structural mirror; the full SQL Server
-- schema has additional columns. Apply during detailed migration step.

-- =============================================================================
-- SECTION 3: SYSTEM CONFIGURATION TABLES
-- =============================================================================

CREATE TABLE public.tblBranches (
    BranchCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BranchID VARCHAR(15) UNIQUE NOT NULL,
    BranchNameAr VARCHAR(200) NOT NULL,
    BranchNameEn VARCHAR(200),
    Address VARCHAR(500),
    City VARCHAR(100),
    Country VARCHAR(100) DEFAULT 'SA',
    Phone VARCHAR(50),
    Email VARCHAR(100),
    ManagerName VARCHAR(200),
    IsMainBranch BOOLEAN DEFAULT FALSE,
    IsActive BOOLEAN DEFAULT TRUE,
    OpenedAt DATE,
    Notes TEXT
);

CREATE TABLE public.tblCompanies (
    CompanyCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyNameAr VARCHAR(200) NOT NULL,
    CompanyNameEn VARCHAR(200),
    TaxNumber VARCHAR(50),
    VATNumber VARCHAR(50),
    Address VARCHAR(500),
    City VARCHAR(100),
    Country VARCHAR(100) DEFAULT 'SA',
    Phone VARCHAR(50),
    Email VARCHAR(100),
    Website VARCHAR(200),
    Logo BYTEA,
    CurrencyCode INT,
    FiscalYearStart DATE,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT
);

CREATE TABLE public.tblCurrencies (
    CurrencyCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CurrencyID VARCHAR(10) UNIQUE NOT NULL,
    CurrencyNameAr VARCHAR(100) NOT NULL,
    CurrencyNameEn VARCHAR(100),
    Symbol VARCHAR(10),
    ExchangeRate NUMERIC(18, 8) DEFAULT 1.0,
    IsBaseCurrency BOOLEAN DEFAULT FALSE,
    IsActive BOOLEAN DEFAULT TRUE,
    LastUpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.tblBanks (
    BankCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BankID VARCHAR(15) UNIQUE NOT NULL,
    BankNameAr VARCHAR(200) NOT NULL,
    BankNameEn VARCHAR(200),
    AccountNumber VARCHAR(50),
    IBAN VARCHAR(50),
    SwiftCode VARCHAR(20),
    BranchName VARCHAR(200),
    CurrencyCode INT,
    OpeningBalance NUMERIC(18, 4) DEFAULT 0,
    CurrentBalance NUMERIC(18, 4) DEFAULT 0,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT
);

CREATE TABLE public.tblFunds (
    FundCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FundID VARCHAR(15) UNIQUE NOT NULL,
    FundNameAr VARCHAR(200) NOT NULL,
    FundNameEn VARCHAR(200),
    FundType VARCHAR(50),
    CurrencyCode INT,
    OpeningBalance NUMERIC(18, 4) DEFAULT 0,
    CurrentBalance NUMERIC(18, 4) DEFAULT 0,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT
);

CREATE TABLE public.tblCostCenters (
    CostCenterCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CostCenterID VARCHAR(15) UNIQUE NOT NULL,
    CostCenterNameAr VARCHAR(200) NOT NULL,
    CostCenterNameEn VARCHAR(200),
    ParentCostCenterCode INT,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT
);

CREATE TABLE public.tblPaymentMethods (
    PaymentMethodCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MethodNameAr VARCHAR(100) NOT NULL,
    MethodNameEn VARCHAR(100),
    MethodType VARCHAR(50), -- CASH / CHEQUE / BANK_TRANSFER / CARD
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT
);

CREATE TABLE public.tblPaymentTerms (
    PaymentTermCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TermNameAr VARCHAR(100) NOT NULL,
    TermNameEn VARCHAR(100),
    DaysCount INT DEFAULT 0,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT
);

CREATE TABLE public.tblPriceLists (
    PriceListCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PriceListNameAr VARCHAR(200) NOT NULL,
    PriceListNameEn VARCHAR(200),
    CurrencyCode INT,
    MarkupPercent NUMERIC(8, 3) DEFAULT 0,
    ValidFrom DATE,
    ValidTo DATE,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT
);

-- =============================================================================
-- SECTION 4: CHART OF ACCOUNTS
-- =============================================================================

CREATE TABLE public.tblAccounts (
    AccountCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountID VARCHAR(50) UNIQUE NOT NULL,
    AccountNameAr VARCHAR(200) NOT NULL,
    AccountNameEn VARCHAR(200),
    AccountType VARCHAR(50) NOT NULL, -- ASSET / LIABILITY / EQUITY / REVENUE / EXPENSE
    ParentAccountCode INT,
    AccountLevel INT DEFAULT 0,
    AccountNature VARCHAR(20) NOT NULL, -- Debit / Credit
    IsMainAccount BOOLEAN DEFAULT FALSE,
    IsPostable BOOLEAN DEFAULT TRUE,
    OpeningBalance NUMERIC(18, 4) DEFAULT 0,
    CurrentBalance NUMERIC(18, 4) DEFAULT 0,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT,
    CONSTRAINT FK_Accounts_Parent FOREIGN KEY (ParentAccountCode) REFERENCES public.tblAccounts (AccountCode)
);

CREATE INDEX idx_tblAccounts_Parent ON public.tblAccounts (ParentAccountCode);

CREATE INDEX idx_tblAccounts_Type ON public.tblAccounts (AccountType);

CREATE INDEX idx_tblAccounts_Active ON public.tblAccounts (IsActive);

-- =============================================================================
-- SECTION 5: FINANCIAL TRANSACTIONS
-- =============================================================================

CREATE TABLE public.tblJournalHeader (
    JournalCode BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JournalID VARCHAR(30) UNIQUE NOT NULL,
    JournalDate DATE NOT NULL,
    FiscalYear INT NOT NULL,
    FiscalPeriod INT NOT NULL,
    Description VARCHAR(500),
    ReferenceNo VARCHAR(100),
    SourceType VARCHAR(50), -- MANUAL / SALES / PURCHASE / BOND
    SourceCode BIGINT,
    CurrencyCode INT,
    ExchangeRate NUMERIC(18, 8) DEFAULT 1.0,
    TotalDebit NUMERIC(18, 4) DEFAULT 0,
    TotalCredit NUMERIC(18, 4) DEFAULT 0,
    IsPosted BOOLEAN DEFAULT FALSE,
    PostedAt TIMESTAMP,
    PostedBy INT,
    ApprovedBy INT,
    ApprovedAt TIMESTAMP,
    IsCancelled BOOLEAN DEFAULT FALSE,
    CancelledAt TIMESTAMP,
    CancelledBy INT,
    CancellationReason TEXT,
    CreatedBy INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ModifiedBy INT,
    ModifiedAt TIMESTAMP,
    Notes TEXT
);

CREATE TABLE public.tblJournalBody (
    JournalDetailID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JournalCode BIGINT NOT NULL,
    LineNumber INT NOT NULL,
    AccountCode INT NOT NULL,
    CostCenterCode INT,
    Description VARCHAR(500),
    Debit NUMERIC(18, 4) DEFAULT 0,
    Credit NUMERIC(18, 4) DEFAULT 0,
    CurrencyCode INT,
    DebitLocal NUMERIC(18, 4) DEFAULT 0,
    CreditLocal NUMERIC(18, 4) DEFAULT 0,
    CONSTRAINT FK_JournalBody_Header FOREIGN KEY (JournalCode) REFERENCES public.tblJournalHeader (JournalCode) ON DELETE CASCADE,
    CONSTRAINT FK_JournalBody_Account FOREIGN KEY (AccountCode) REFERENCES public.tblAccounts (AccountCode)
);

CREATE INDEX idx_JournalBody_Journal ON public.tblJournalBody (JournalCode);

CREATE INDEX idx_JournalBody_Account ON public.tblJournalBody (AccountCode);

CREATE TABLE public.tblBondHeader (
    BondCode BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BondID VARCHAR(30) UNIQUE NOT NULL,
    BondType VARCHAR(20) NOT NULL, -- RECEIPT / PAYMENT
    BondDate DATE NOT NULL,
    FiscalYear INT NOT NULL,
    FiscalPeriod INT NOT NULL,
    Amount NUMERIC(18, 4) NOT NULL,
    CurrencyCode INT,
    ExchangeRate NUMERIC(18, 8) DEFAULT 1.0,
    PaymentMethodCode INT,
    BankCode INT,
    FundCode INT,
    CustomerCode INT,
    SupplierCode INT,
    AccountCode INT, -- cash/bank account
    Description VARCHAR(500),
    ReferenceNo VARCHAR(100),
    IsPosted BOOLEAN DEFAULT FALSE,
    PostedAt TIMESTAMP,
    PostedBy INT,
    CreatedBy INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Notes TEXT
);

CREATE TABLE public.tblBondBody (
    BondDetailID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BondCode BIGINT NOT NULL,
    LineNumber INT NOT NULL,
    AccountCode INT NOT NULL,
    CostCenterCode INT,
    Description VARCHAR(500),
    Debit NUMERIC(18, 4) DEFAULT 0,
    Credit NUMERIC(18, 4) DEFAULT 0,
    CONSTRAINT FK_BondBody_Header FOREIGN KEY (BondCode) REFERENCES public.tblBondHeader (BondCode) ON DELETE CASCADE,
    CONSTRAINT FK_BondBody_Account FOREIGN KEY (AccountCode) REFERENCES public.tblAccounts (AccountCode)
);

-- =============================================================================
-- SECTION 6: INVENTORY DOMAIN
-- =============================================================================

CREATE TABLE public.tblCategories (
    CategoryCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryID VARCHAR(15) UNIQUE NOT NULL,
    CategoryNameAr VARCHAR(200) NOT NULL,
    CategoryNameEn VARCHAR(200),
    ParentCategoryCode INT,
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT,
    CONSTRAINT FK_Categories_Parent FOREIGN KEY (ParentCategoryCode) REFERENCES public.tblCategories (CategoryCode)
);

CREATE TABLE public.tblUnits (
    UnitCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UnitID VARCHAR(15) UNIQUE NOT NULL,
    UnitNameAr VARCHAR(100) NOT NULL,
    UnitNameEn VARCHAR(100),
    Symbol VARCHAR(20),
    IsActive BOOLEAN DEFAULT TRUE
);

CREATE TABLE public.tblStores (
    StoreCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StoreID VARCHAR(15) UNIQUE NOT NULL,
    StoreNameAr VARCHAR(200) NOT NULL,
    StoreNameEn VARCHAR(200),
    BranchCode INT,
    ManagerName VARCHAR(200),
    IsActive BOOLEAN DEFAULT TRUE,
    Notes TEXT,
    CONSTRAINT FK_Stores_Branch FOREIGN KEY (BranchCode) REFERENCES public.tblBranches (BranchCode)
);

CREATE TABLE public.tblProducts (
    ProductCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductID VARCHAR(50) UNIQUE NOT NULL,
    ProductNameAr VARCHAR(200) NOT NULL,
    ProductNameEn VARCHAR(200),
    Barcode VARCHAR(50),
    CategoryCode INT,
    DefaultUnitCode INT,
    IsInventoryItem BOOLEAN DEFAULT TRUE,
    StandardCost NUMERIC(18, 4) DEFAULT 0,
    LastPurchasePrice NUMERIC(18, 4) DEFAULT 0,
    LastSalePrice NUMERIC(18, 4) DEFAULT 0,
    MinStockLevel NUMERIC(18, 4) DEFAULT 0,
    MaxStockLevel NUMERIC(18, 4) DEFAULT 0,
    ReorderLevel NUMERIC(18, 4) DEFAULT 0,
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedBy INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Notes TEXT,
    CONSTRAINT FK_Products_Category FOREIGN KEY (CategoryCode) REFERENCES public.tblCategories (CategoryCode),
    CONSTRAINT FK_Products_Unit FOREIGN KEY (DefaultUnitCode) REFERENCES public.tblUnits (UnitCode)
);

CREATE TABLE public.tblProductBatches (
    BatchID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductCode INT NOT NULL,
    BatchNo VARCHAR(50) NOT NULL,
    ExpiryDate DATE,
    ManufactureDate DATE,
    CONSTRAINT FK_Batches_Product FOREIGN KEY (ProductCode) REFERENCES public.tblProducts (ProductCode)
);

CREATE TABLE public.tblStoreProducts (
    StoreProductID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StoreCode INT NOT NULL,
    ProductCode INT NOT NULL,
    BatchID INT,
    QtyOnHand NUMERIC(18, 4) DEFAULT 0,
    QtyReserved NUMERIC(18, 4) DEFAULT 0,
    AvgCost NUMERIC(18, 4) DEFAULT 0,
    LastCost NUMERIC(18, 4) DEFAULT 0,
    LocationInStore VARCHAR(50),
    IsActive BOOLEAN DEFAULT TRUE,
    CONSTRAINT FK_StoreProducts_Store FOREIGN KEY (StoreCode) REFERENCES public.tblStores (StoreCode),
    CONSTRAINT FK_StoreProducts_Product FOREIGN KEY (ProductCode) REFERENCES public.tblProducts (ProductCode),
    CONSTRAINT FK_StoreProducts_Batch FOREIGN KEY (BatchID) REFERENCES public.tblProductBatches (BatchID),
    CONSTRAINT UQ_StoreProduct_Batch UNIQUE (
        StoreCode,
        ProductCode,
        BatchID
    )
);

CREATE TABLE public.tblProductPricing (
    PricingID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductCode INT NOT NULL,
    PriceListCode INT NOT NULL,
    UnitCode INT NOT NULL,
    Price NUMERIC(18, 4) NOT NULL,
    MinQuantity NUMERIC(18, 4) DEFAULT 1,
    ValidFrom DATE,
    ValidTo DATE,
    CONSTRAINT FK_Pricing_Product FOREIGN KEY (ProductCode) REFERENCES public.tblProducts (ProductCode),
    CONSTRAINT FK_Pricing_PriceList FOREIGN KEY (PriceListCode) REFERENCES public.tblPriceLists (PriceListCode),
    CONSTRAINT FK_Pricing_Unit FOREIGN KEY (UnitCode) REFERENCES public.tblUnits (UnitCode)
);

CREATE TABLE public.tblProductImages (
    ImageID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductCode INT NOT NULL,
    ImageData BYTEA,
    Caption VARCHAR(200),
    IsPrimary BOOLEAN DEFAULT FALSE,
    SortOrder INT DEFAULT 0,
    CONSTRAINT FK_Images_Product FOREIGN KEY (ProductCode) REFERENCES public.tblProducts (ProductCode) ON DELETE CASCADE
);

-- =============================================================================
-- SECTION 7: TRANSACTION DOMAIN (Customers / Suppliers / Operations)
-- =============================================================================

CREATE TABLE public.tblCustomers (
    CustomerCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID VARCHAR(15) UNIQUE NOT NULL,
    CustomerNameAr VARCHAR(200) NOT NULL,
    CustomerNameEn VARCHAR(200),
    CustomerType VARCHAR(50) DEFAULT 'INDIVIDUAL',
    TaxNumber VARCHAR(50),
    VATNumber VARCHAR(50),
    Address VARCHAR(500),
    City VARCHAR(100),
    Country VARCHAR(100) DEFAULT 'SA',
    Phone VARCHAR(50),
    Mobile VARCHAR(50),
    Email VARCHAR(100),
    BranchCode INT,
    PriceListCode INT,
    PaymentTermCode INT,
    CreditLimit NUMERIC(18, 4) DEFAULT 0,
    CurrentCredit NUMERIC(18, 4) DEFAULT 0,
    AvailableCredit NUMERIC(18, 4) GENERATED ALWAYS AS (CreditLimit - CurrentCredit) STORED,
    PaymentDays INT DEFAULT 0,
    Balance NUMERIC(18, 4) DEFAULT 0,
    TotalSales NUMERIC(18, 4) DEFAULT 0,
    LastSaleDate DATE,
    CustomerSince DATE,
    IsActive BOOLEAN DEFAULT TRUE,
    IsBlocked BOOLEAN DEFAULT FALSE,
    Notes TEXT,
    CONSTRAINT FK_Customers_Branch FOREIGN KEY (BranchCode) REFERENCES public.tblBranches (BranchCode),
    CONSTRAINT FK_Customers_PriceList FOREIGN KEY (PriceListCode) REFERENCES public.tblPriceLists (PriceListCode),
    CONSTRAINT FK_Customers_PaymentTerm FOREIGN KEY (PaymentTermCode) REFERENCES public.tblPaymentTerms (PaymentTermCode)
);

CREATE TABLE public.tblCustomerContacts (
    ContactID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerCode INT NOT NULL,
    ContactName VARCHAR(200),
    JobTitle VARCHAR(100),
    Phone VARCHAR(50),
    Mobile VARCHAR(50),
    Email VARCHAR(100),
    IsPrimary BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_CustomerContacts_Customer FOREIGN KEY (CustomerCode) REFERENCES public.tblCustomers (CustomerCode) ON DELETE CASCADE
);

CREATE TABLE public.tblSuppliers (
    SupplierCode INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupplierID VARCHAR(15) UNIQUE NOT NULL,
    SupplierNameAr VARCHAR(200) NOT NULL,
    SupplierNameEn VARCHAR(200),
    SupplierType VARCHAR(50) DEFAULT 'INDIVIDUAL',
    TaxNumber VARCHAR(50),
    VATNumber VARCHAR(50),
    Address VARCHAR(500),
    City VARCHAR(100),
    Country VARCHAR(100) DEFAULT 'SA',
    Phone VARCHAR(50),
    Mobile VARCHAR(50),
    Email VARCHAR(100),
    BranchCode INT,
    PaymentTermCode INT,
    BankName VARCHAR(200),
    AccountNumber VARCHAR(50),
    IBAN VARCHAR(50),
    SwiftCode VARCHAR(20),
    CreditLimit NUMERIC(18, 4) DEFAULT 0,
    CurrentCredit NUMERIC(18, 4) DEFAULT 0,
    AvailableCredit NUMERIC(18, 4) GENERATED ALWAYS AS (CreditLimit - CurrentCredit) STORED,
    PaymentDays INT DEFAULT 0,
    Balance NUMERIC(18, 4) DEFAULT 0,
    TotalPurchases NUMERIC(18, 4) DEFAULT 0,
    LastPurchaseDate DATE,
    SupplierSince DATE,
    IsActive BOOLEAN DEFAULT TRUE,
    IsBlocked BOOLEAN DEFAULT FALSE,
    Notes TEXT,
    CONSTRAINT FK_Suppliers_Branch FOREIGN KEY (BranchCode) REFERENCES public.tblBranches (BranchCode),
    CONSTRAINT FK_Suppliers_PaymentTerm FOREIGN KEY (PaymentTermCode) REFERENCES public.tblPaymentTerms (PaymentTermCode)
);

CREATE TABLE public.tblSupplierContacts (
    ContactID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupplierCode INT NOT NULL,
    ContactName VARCHAR(200),
    JobTitle VARCHAR(100),
    Phone VARCHAR(50),
    Mobile VARCHAR(50),
    Email VARCHAR(100),
    IsPrimary BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_SupplierContacts_Supplier FOREIGN KEY (SupplierCode) REFERENCES public.tblSuppliers (SupplierCode) ON DELETE CASCADE
);

-- Operations (Sales / Purchases / Returns)
CREATE TABLE public.tblOperationHeader (
    OperationCode BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OperationID VARCHAR(30) UNIQUE NOT NULL,
    OperationType VARCHAR(20) NOT NULL, -- SALE / PURCHASE / SALE_RETURN / PURCHASE_RETURN
    OperationDate DATE NOT NULL,
    FiscalYear INT NOT NULL,
    FiscalPeriod INT NOT NULL,
    CustomerCode INT,
    SupplierCode INT,
    BranchCode INT,
    StoreCode INT,
    CurrencyCode INT,
    ExchangeRate NUMERIC(18, 8) DEFAULT 1.0,
    SubTotal NUMERIC(18, 4) DEFAULT 0,
    DiscountPercent NUMERIC(8, 3) DEFAULT 0,
    DiscountAmount NUMERIC(18, 4) DEFAULT 0,
    TaxAmount NUMERIC(18, 4) DEFAULT 0,
    AdditionalCharges NUMERIC(18, 4) DEFAULT 0,
    Total NUMERIC(18, 4) DEFAULT 0,
    PaidAmount NUMERIC(18, 4) DEFAULT 0,
    RemainingAmount NUMERIC(18, 4) DEFAULT 0,
    PaymentMethodCode INT,
    ReferenceNo VARCHAR(100),
    Description VARCHAR(500),
    IsPosted BOOLEAN DEFAULT FALSE,
    PostedAt TIMESTAMP,
    PostedBy INT,
    IsCancelled BOOLEAN DEFAULT FALSE,
    CreatedBy INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Notes TEXT,
    CONSTRAINT FK_OpHeader_Customer FOREIGN KEY (CustomerCode) REFERENCES public.tblCustomers (CustomerCode),
    CONSTRAINT FK_OpHeader_Supplier FOREIGN KEY (SupplierCode) REFERENCES public.tblSuppliers (SupplierCode),
    CONSTRAINT FK_OpHeader_Branch FOREIGN KEY (BranchCode) REFERENCES public.tblBranches (BranchCode),
    CONSTRAINT FK_OpHeader_Store FOREIGN KEY (StoreCode) REFERENCES public.tblStores (StoreCode),
    CONSTRAINT FK_OpHeader_Currency FOREIGN KEY (CurrencyCode) REFERENCES public.tblCurrencies (CurrencyCode),
    CONSTRAINT FK_OpHeader_PaymentMethod FOREIGN KEY (PaymentMethodCode) REFERENCES public.tblPaymentMethods (PaymentMethodCode)
);

CREATE TABLE public.tblOperationBody (
    OperationDetailID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OperationCode BIGINT NOT NULL,
    LineNumber INT NOT NULL,
    ProductCode INT NOT NULL,
    UnitCode INT,
    BatchID INT,
    Quantity NUMERIC(18, 4) DEFAULT 0,
    UnitPrice NUMERIC(18, 4) DEFAULT 0,
    Cost NUMERIC(18, 4) DEFAULT 0,
    DiscountPercent NUMERIC(8, 3) DEFAULT 0,
    DiscountAmount NUMERIC(18, 4) DEFAULT 0,
    TaxPercent NUMERIC(8, 3) DEFAULT 0,
    TaxAmount NUMERIC(18, 4) DEFAULT 0,
    Total NUMERIC(18, 4) DEFAULT 0,
    StoreCode INT,
    Description VARCHAR(500),
    CONSTRAINT FK_OpBody_Header FOREIGN KEY (OperationCode) REFERENCES public.tblOperationHeader (OperationCode) ON DELETE CASCADE,
    CONSTRAINT FK_OpBody_Product FOREIGN KEY (ProductCode) REFERENCES public.tblProducts (ProductCode),
    CONSTRAINT FK_OpBody_Unit FOREIGN KEY (UnitCode) REFERENCES public.tblUnits (UnitCode),
    CONSTRAINT FK_OpBody_Batch FOREIGN KEY (BatchID) REFERENCES public.tblProductBatches (BatchID)
);

CREATE TABLE public.tblOperationTaxes (
    OperationTaxID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OperationCode BIGINT NOT NULL,
    TaxType VARCHAR(50),
    TaxPercent NUMERIC(8, 3) DEFAULT 0,
    TaxAmount NUMERIC(18, 4) DEFAULT 0,
    CONSTRAINT FK_OpTaxes_Header FOREIGN KEY (OperationCode) REFERENCES public.tblOperationHeader (OperationCode) ON DELETE CASCADE
);

CREATE TABLE public.tblProductMovement (
    MovementID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductCode INT NOT NULL,
    StoreCode INT NOT NULL,
    MovementType VARCHAR(20) NOT NULL, -- IN / OUT / TRANSFER / ADJUST
    MovementDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Quantity NUMERIC(18, 4) NOT NULL,
    UnitCost NUMERIC(18, 4) DEFAULT 0,
    ReferenceType VARCHAR(50), -- SALE / PURCHASE / ADJUST
    ReferenceCode BIGINT,
    BatchID INT,
    Notes TEXT,
    CONSTRAINT FK_Movement_Product FOREIGN KEY (ProductCode) REFERENCES public.tblProducts (ProductCode),
    CONSTRAINT FK_Movement_Store FOREIGN KEY (StoreCode) REFERENCES public.tblStores (StoreCode)
);

-- =============================================================================
-- END OF TABLES
-- =============================================================================
SELECT 'IntegratedAccSys PostgreSQL schema created successfully.' AS message;