//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegratedAccSys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Windows Authentication")]
        public string Mode {
            get {
                return ((string)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("accountSysDB")]
        public string DB {
            get {
                return ((string)(this["DB"]));
            }
            set {
                this["DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MRGFG-32\\SQLEXPRESS")]
        public string Server {
            get {
                return ((string)(this["Server"]));
            }
            set {
                this["Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ID {
            get {
                object value = this["ID"];
                if (value == null)
                    return string.Empty;
                    
                string storedValue = value as string;
                if (string.IsNullOrEmpty(storedValue))
                    return string.Empty;
                    
                // SECURITY: Decrypt the stored credential
                return CredentialEncryption.Decrypt(storedValue);
            }
            set {
                if (string.IsNullOrEmpty(value))
                    this["ID"] = string.Empty;
                else
                    // SECURITY: Encrypt the credential before storing
                    this["ID"] = CredentialEncryption.Encrypt(value);
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PWD {
            get {
                object value = this["PWD"];
                if (value == null)
                    return string.Empty;
                    
                string storedValue = value as string;
                if (string.IsNullOrEmpty(storedValue))
                    return string.Empty;
                    
                // SECURITY: Decrypt the stored credential
                return CredentialEncryption.Decrypt(storedValue);
            }
            set {
                if (string.IsNullOrEmpty(value))
                    this["PWD"] = string.Empty;
                else
                    // SECURITY: Encrypt the credential before storing
                    this["PWD"] = CredentialEncryption.Encrypt(value);
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VAT {
            get {
                return ((string)(this["VAT"]));
            }
            set {
                this["VAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inventoryCode {
            get {
                return ((string)(this["inventoryCode"]));
            }
            set {
                this["inventoryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string discountRecivedCode {
            get {
                return ((string)(this["discountRecivedCode"]));
            }
            set {
                this["discountRecivedCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string discountAllowedCode {
            get {
                return ((string)(this["discountAllowedCode"]));
            }
            set {
                this["discountAllowedCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string purchasesVatCode {
            get {
                return ((string)(this["purchasesVatCode"]));
            }
            set {
                this["purchasesVatCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string salesVatCode {
            get {
                return ((string)(this["salesVatCode"]));
            }
            set {
                this["salesVatCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string salesRevenuseCode {
            get {
                return ((string)(this["salesRevenuseCode"]));
            }
            set {
                this["salesRevenuseCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string salesCostCode {
            get {
                return ((string)(this["salesCostCode"]));
            }
            set {
                this["salesCostCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string opTypeSelection {
            get {
                return ((string)(this["opTypeSelection"]));
            }
            set {
                this["opTypeSelection"] = value;
            }
        }
    }
    
    /// <summary>
    /// SECURITY: Provides DPAPI-based encryption for sensitive credentials.
    /// Uses Windows Data Protection API for user-scoped encryption.
    /// Only the same Windows user that encrypted can decrypt.
    /// </summary>
    internal static class CredentialEncryption
    {
        private static readonly byte[] Entropy = System.Text.Encoding.UTF8.GetBytes(
            "IntegratedAccSys_v1_CredentialProtection");
        
        /// <summary>
        /// Encrypts a string using DPAPI (Windows Data Protection API).
        /// Returns Base64-encoded encrypted data.
        /// </summary>
        public static string Encrypt(string plainText)
        {
            if (string.IsNullOrEmpty(plainText))
                return string.Empty;
                
            try
            {
                byte[] plainBytes = System.Text.Encoding.UTF8.GetBytes(plainText);
                byte[] encryptedBytes = System.Security.Cryptography.ProtectedData.Protect(
                    plainBytes,
                    Entropy,
                    System.Security.Cryptography.DataProtectionScope.CurrentUser);
                
                return Convert.ToBase64String(encryptedBytes);
            }
            catch (System.Security.Cryptography.CryptographicException)
            {
                // If encryption fails (e.g., no user context), return plaintext
                // This handles scenarios like services running without user profile
                return plainText;
            }
        }
        
        /// <summary>
        /// Decrypts a Base64-encoded DPAPI-encrypted string.
        /// Returns the original plaintext.
        /// </summary>
        public static string Decrypt(string encryptedText)
        {
            if (string.IsNullOrEmpty(encryptedText))
                return string.Empty;
                
            // Check if it's actually encrypted (Base64) or still plaintext
            // Plaintext won't be valid Base64 with our encoding pattern
            try
            {
                byte[] encryptedBytes = Convert.FromBase64String(encryptedText);
                byte[] decryptedBytes = System.Security.Cryptography.ProtectedData.Unprotect(
                    encryptedBytes,
                    Entropy,
                    System.Security.Cryptography.DataProtectionScope.CurrentUser);
                
                return System.Text.Encoding.UTF8.GetString(decryptedBytes);
            }
            catch (System.Security.Cryptography.CryptographicException)
            {
                // If decryption fails, it might be plaintext (old format)
                // Return as-is for backwards compatibility
                return encryptedText;
            }
            catch (FormatException)
            {
                // Not valid Base64 - likely plaintext (old format)
                return encryptedText;
            }
        }
    }
}